# Generated by Django 5.0.7 on 2024-07-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('author', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=18, unique=True)),
                ('genre', models.CharField(max_length=25)),
                ('published_date', models.CharField()),
            ],
        ),
    ]
